In [1]:
import pandas as pd

df = pd.read_csv("ds_salaries.csv")
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

In [3]:
df.describe()

       Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [4]:
df.groupby("job_title")["salary_in_usd"].median().sort_values(ascending=False)

job_title
Data Analytics Lead                         405000.0
Financial Data Analyst                      275000.0
Head of Data                                200000.0
Principal Data Engineer                     200000.0
Data Architect                              180000.0
Analytics Engineer                          179850.0
Principal Data Scientist                    173762.0
Director of Data Science                    168000.0
Data Specialist                             165000.0
Applied Data Scientist                      157000.0
Director of Data Engineering                156738.0
Machine Learning Scientist                  156500.0
Data Science Manager                        155750.0
Data Engineering Manager                    150000.0
Head of Data Science                        138937.5
Cloud Data Engineer                         124647.0
Principal Data Analyst                      122500.0
Lead Data Engineer                          121593.5
Data Analytics Manager                      120000.0
Machine Learning Manager                    117104.0
Lead Data Scientist                         115000.0
Data Engineer                               105500.0
Staff Data Scientist                        105000.0
Data Scientist                              103691.0
Big Data Architect                           99703.0
Computer Vision Software Engineer            95746.0
Data Analyst                                 90320.0
Marketing Data Analyst                       88654.0
Lead Machine Learning Engineer               87932.0
Machine Learning Engineer                    87932.0
Lead Data Analyst                            87000.0
Head of Machine Learning                     79039.0
Machine Learning Developer                   78791.0
Data Science Consultant                      76833.0
BI Data Analyst                              76500.0
Research Scientist                           76263.5
Business Data Analyst                        70912.0
ML Engineer                                  70537.5
Data Analytics Engineer                      64598.5
Finance Data Analyst                         61896.0
Data Science Engineer                        60000.0
Machine Learning Infrastructure Engineer     58255.0
Applied Machine Learning Scientist           56700.0
ETL Developer                                54957.0
AI Scientist                                 45896.0
Big Data Engineer                            41305.5
NLP Engineer                                 37236.0
Computer Vision Engineer                     26304.5
Product Data Analyst                         13036.0
3D Computer Vision Researcher                 5409.0
Name: salary_in_usd, dtype: float64

In [5]:
df.groupby("job_title")["salary_in_usd"].agg(["median", "count"]).sort_values(by="median", ascending=False)

                                            median  count
job_title
Data Analytics Lead                       405000.0      1
Financial Data Analyst                    275000.0      2
Head of Data                              200000.0      5
Principal Data Engineer                   200000.0      3
Data Architect                            180000.0     11
Analytics Engineer                        179850.0      4
Principal Data Scientist                  173762.0      7
Director of Data Science                  168000.0      7
Data Specialist                           165000.0      1
Applied Data Scientist                    157000.0      5
Director of Data Engineering              156738.0      2
Machine Learning Scientist                156500.0      8
Data Science Manager                      155750.0     12
Data Engineering Manager                  150000.0      5
Head of Data Science                      138937.5      4
Cloud Data Engineer                       124647.0      2
Principal Data Analyst                    122500.0      2
Lead Data Engineer                        121593.5      6
Data Analytics Manager                    120000.0      7
Machine Learning Manager                  117104.0      1
Lead Data Scientist                       115000.0      3
Data Engineer                             105500.0    132
Staff Data Scientist                      105000.0      1
Data Scientist                            103691.0    143
Big Data Architect                         99703.0      1
Computer Vision Software Engineer          95746.0      3
Data Analyst                               90320.0     97
Marketing Data Analyst                     88654.0      1
Lead Machine Learning Engineer             87932.0      1
Machine Learning Engineer                  87932.0     41
Lead Data Analyst                          87000.0      3
Head of Machine Learning                   79039.0      1
Machine Learning Developer                 78791.0      3
Data Science Consultant                    76833.0      7
BI Data Analyst                            76500.0      6
Research Scientist                         76263.5     16
Business Data Analyst                      70912.0      5
ML Engineer                                70537.5      6
Data Analytics Engineer                    64598.5      4
Finance Data Analyst                       61896.0      1
Data Science Engineer                      60000.0      3
Machine Learning Infrastructure Engineer   58255.0      3
Applied Machine Learning Scientist         56700.0      4
ETL Developer                              54957.0      2
AI Scientist                               45896.0      7
Big Data Engineer                          41305.5      8
NLP Engineer                               37236.0      1
Computer Vision Engineer                   26304.5      6
Product Data Analyst                       13036.0      2
3D Computer Vision Researcher               5409.0      1

In [6]:
df_filtered = df.groupby("job_title")["salary_in_usd"].agg(["median", "count"])
df_filtered = df_filtered[df_filtered["count"] >= 10]
df_filtered.sort_values(by="median", ascending=False)

                             median  count
job_title
Data Architect             180000.0     11
Data Science Manager       155750.0     12
Data Engineer              105500.0    132
Data Scientist             103691.0    143
Data Analyst                90320.0     97
Machine Learning Engineer   87932.0     41
Research Scientist          76263.5     16

In [7]:
df[df["job_title"] == "Data Scientist"]["salary_in_usd"].describe()

count       143.000000
mean     108187.832168
std       64112.840519
min        2859.000000
25%       54724.000000
50%      103691.000000
75%      140850.000000
max      412000.000000
Name: salary_in_usd, dtype: float64

In [8]:
df[df["job_title"] == "Data Engineer"]["salary_in_usd"].describe()

count       132.000000
mean     112725.000000
std       57629.082107
min        4000.000000
25%       70039.500000
50%      105500.000000
75%      154600.000000
max      324000.000000
Name: salary_in_usd, dtype: float64

In [9]:
df[df["job_title"] == "Data Analyst"]["salary_in_usd"].describe()

count        97.000000
mean      92893.061856
std       39961.075848
min        6072.000000
25%       62000.000000
50%       90320.000000
75%      116150.000000
max      200000.000000
Name: salary_in_usd, dtype: float64

In [11]:
df.groupby("experience_level")["salary_in_usd"].median()

experience_level
EN     56500.0
EX    171437.5
MI     76940.0
SE    135500.0
Name: salary_in_usd, dtype: float64

In [12]:
df.groupby("company_location")["salary_in_usd"].median().sort_values(ascending=False)

company_location
RU    157500.0
US    135000.0
NZ    125000.0
IL    119059.0
AE    115000.0
DZ    100000.0
IQ    100000.0
SG     89294.0
AU     87425.0
BE     85699.0
CA     81895.5
GB     78526.0
DE     78015.0
JP     75682.0
CN     71665.5
IE     71444.0
AT     69489.5
CH     64114.0
SI     63831.0
RO     60000.0
LU     59102.0
FR     56738.0
PT     54217.5
NL     54021.0
CZ     50937.0
GR     49461.0
ES     48371.5
DK     45896.0
HR     45618.0
PL     41093.5
CL     40038.0
MY     40000.0
IT     36366.5
HU     35735.0
MX     33511.0
EE     32974.0
NG     30000.0
MT     28369.0
IN     22124.0
CO     21844.0
TR     20171.0
HN     20000.0
BR     18907.0
AS     18053.0
MD     18000.0
UA     13400.0
PK     12000.0
KE      9272.0
IR      4000.0
VN      4000.0
Name: salary_in_usd, dtype: float64

In [13]:
df.groupby("company_location")["salary_in_usd"].agg(["median", "count"]).sort_values(by="median", ascending=False)

                    median  count
company_location
RU                157500.0      2
US                135000.0    355
NZ                125000.0      1
IL                119059.0      1
AE                115000.0      3
DZ                100000.0      1
IQ                100000.0      1
SG                 89294.0      1
AU                 87425.0      3
BE                 85699.0      2
CA                 81895.5     30
GB                 78526.0     47
DE                 78015.0     28
JP                 75682.0      6
CN                 71665.5      2
IE                 71444.0      1
AT                 69489.5      4
CH                 64114.0      2
SI                 63831.0      2
RO                 60000.0      1
LU                 59102.0      3
FR                 56738.0     15
PT                 54217.5      4
NL                 54021.0      4
CZ                 50937.0      2
GR                 49461.0     11
ES                 48371.5     14
DK                 45896.0      3
HR                 45618.0      1
PL                 41093.5      4
CL                 40038.0      1
MY                 40000.0      1
IT                 36366.5      2
HU                 35735.0      1
MX                 33511.0      3
EE                 32974.0      1
NG                 30000.0      2
MT                 28369.0      1
IN                 22124.0     24
CO                 21844.0      1
TR                 20171.0      3
HN                 20000.0      1
BR                 18907.0      3
AS                 18053.0      1
MD                 18000.0      1
UA                 13400.0      1
PK                 12000.0      3
KE                  9272.0      1
IR                  4000.0      1
VN                  4000.0      1